---
- hosts: all
  tasks:
    - name: install nginx
      apt: 
        name: nginx 
        state: present        

    - name: Delete default config and simlink
      file:
        state: absent
        path: /etc/nginx/{{ item }}/default
      loop:
        - sites-available
        - sites-enabled

    - name: Copy virtualhosts configs to host
      template:
        src: templates/{{ item.temp }}
        dest: /etc/nginx/{{ item.conf }}
        owner: root
        mode: '0644'
      vars:
        worker_processes: 1
        worker_connections: 512  
      loop:
        - temp: bulutovstas.devops.rebrain.srwx.net_80.j2
          conf: sites-available/bulutovstas.devops.rebrain.srwx.net_80.conf
        - temp: bulutovstas.devops.rebrain.srwx.net_81.j2
          conf: sites-available/bulutovstas.devops.rebrain.srwx.net_81.conf
        - temp: nginx.conf.j2
          conf: nginx.conf
      notify: reload nginx

    - name: Get a list of all vhosts
      find:
        paths: /etc/nginx/sites-available
        patterns: "*.conf"
        file_type: file
      register: find

    - name: Apply symlinks in sites-enabled
      file:
        dest: /etc/nginx/sites-enabled/{{ item.path | basename }}
        src: "{{ item.path }}"
        state: link
        force: yes
      with_items: "{{ find.files }}"
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: start nginx
      service:
        name: nginx
        state: started

