---
- hosts: all
  tasks:
    - name: install nginx
      apt: 
        name: nginx 
        state: present        
      notify: start nginx

    - name: Copy nginx.conf to host
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        mode: '0644'
      vars:
        worker_processes: 1
        worker_connections: 512
      notify: reload nginx

    - name: Delete default config and simlink
      file:
        state: absent
        path: /etc/nginx/{{ item }}/default
      loop:
        - sites-available
        - sites-enabled

    - name: Copy virtualhosts configs to host
      template:
        src: "{{ item }}.j2"
        dest: /etc/nginx/conf.d/{{ item }}.conf
        owner: root
        mode: '0644'
      loop:
        - bulutovstas.devops.rebrain.srwx.net_80
        - bulutovstas.devops.rebrain.srwx.net_81
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

    - name: start nginx
      service:
        name: nginx
        state: started

