---
- hosts: all
  tasks:
    - name: install nginx
      apt: 
        name: nginx 
        state: present

  handlers:
    - name: start nginx
      service:
        name: nginx
        state: started
